FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["EHealthCare1.csproj", ""]
RUN dotnet restore "./EHealthCare1.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "EHealthCare1.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EHealthCare1.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EHealthCare1.dll"]